# Generated by Django 4.0.5 on 2022-07-05 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appfamiliares', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familiares',
            new_name='Familiar',
        ),
    ]
