# Generated by Django 4.0.5 on 2022-07-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appfamiliares', '0003_familiar_apellido_familiar_edad_familiar_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='fecha_nac',
            field=models.DateField(default='10-12-20'),
            preserve_default=False,
        ),
    ]
