# Generated by Django 4.0.5 on 2022-07-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appfamiliares', '0005_remove_familiar_fecha_nac'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-10-20'),
            preserve_default=False,
        ),
    ]
